"""Add User model

Revision ID: 2a5f7141d494
Revises: 0003_findings_extra
Create Date: 2025-12-05 16:48:33.393390

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2a5f7141d494'
down_revision = '0003_findings_extra'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.execute("ALTER TABLE IF EXISTS findings ALTER COLUMN extra TYPE JSON USING extra::json")
    op.execute("ALTER TABLE IF EXISTS studies ALTER COLUMN source DROP DEFAULT")
    op.execute("ALTER TABLE IF EXISTS studies ALTER COLUMN source SET NOT NULL")
    op.execute("ALTER TABLE IF EXISTS studies ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE IF EXISTS studies ALTER COLUMN created_at SET NOT NULL")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS studies ALTER COLUMN created_at DROP NOT NULL")
    op.execute("ALTER TABLE IF EXISTS studies ALTER COLUMN created_at SET DEFAULT NOW()")
    op.execute("ALTER TABLE IF EXISTS studies ALTER COLUMN source DROP NOT NULL")
    op.execute("ALTER TABLE IF EXISTS studies ALTER COLUMN source SET DEFAULT 'upload'")
    op.execute("ALTER TABLE IF EXISTS findings ALTER COLUMN extra TYPE JSONB USING extra::jsonb")
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


